name: android_build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: 'project'

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: $${{ runner.os }}-gradle-$${{ hashFiles('**/*.gradle*') }}

      - name: Build with Gradle
        working-directory: ./project
        run: |
          ./gradlew assembleDebug --stacktrace --no-daemon
        env:
          CI: true

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: project/app/build/outputs/apk/debug/*.apk
          retention-days: 7

