name: android_build
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Clone TVBoxOS repository
        run: git clone --depth=1 https://github.com/fanfan123fanfan/TVBoxOS.git

      - name: Build the app
        working-directory: ./TVBoxOS
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: TVBoxOS-APK
          path: TVBoxOS/app/build/outputs/apk/debug/*.apk
