name: android_build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - id: get-project
        name: Get project name
        run: |
          echo "PROJECT=$$(cat project-to-build | tr -d '\n')" >> $$GITHUB_OUTPUT
          echo "Cloning URL: $$(cat project-to-build)"

      - name: Clone project
        run: git clone --depth=1 "$${{ steps.get-project.outputs.PROJECT }}" project

      - name: Build the app
        working-directory: ./project
        run: |
          if [ ! -f "gradlew" ]; then gradle wrapper; fi
          chmod +x gradlew
          ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-build-apk
          path: project/app/build/outputs/apk/debug/*.apk
